name: Scrape Talk Locations

on:
  push:
    branches:
      - master        # change to 'main' if your default branch is main
    paths:
      - 'talks/**'
      - 'talkmap.ipynb'

# Allow the workflow to push back to the repo
permissions:
  contents: write

# Avoid two runs clobbering each other when they overlap
concurrency:
  group: scrape-talks-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0            # IMPORTANT for pull/rebase
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter pandas requests beautifulsoup4 geopy
          pip install --upgrade getorg

      - name: Execute notebook
        run: |
          jupyter nbconvert --to notebook --execute talkmap.ipynb --output talkmap_out.ipynb

      - name: Configure Git author
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # Rebase onto the latest remote to avoid non-fast-forward errors
      - name: Rebase onto origin/master
        run: |
          git fetch origin master
          git rebase origin/master || (echo "Rebase failed; aborting." && git rebase --abort && exit 1)

      - name: Commit changes (if any)
        run: |
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "Automated update of talk locations"

      # Use --force-with-lease to be robust to rare race conditions between rebase and push
      - name: Push
        run: |
          git push --force-with-lease origin HEAD:master
